Develop to main
uw-it-aca/mdot pull request #323
Opened 2023-04-14 21:40 UTC by abztrakt

2023-04-14 21:44 UTC, David-Strupinski requested changes

2023-04-14 21:44 UTC, David-Strupinski commented on .vscode/extensions.json
the .vscode/ directory should be added to .gitignore

2023-04-14 21:44 UTC, David-Strupinski commented on .vscode/settings.json
same as above

2023-05-17 20:58 UTC, abztrakt commented
Now still a draft until the rest of task/mdot-113 is completed and merged.

2023-06-06 22:52 UTC, closed without merging